version: 0.2  # version
phases:
  # install:
  #   runtime-versions:
  #     terraform: v1.4.5 # it will install terraform v1.4.5 on the web server
  pre_build:
    commands:
      - echo WE ARE ENTERING THE PREBUILD PHASE...
      - terraform init
      - terraform validate
      
  build:
    commands:
      # - terraform plan -var-file="cicdpipeline.tfvars"
      - terraform plan
      # - terraform apply -auto-approve -var-file="cicdpipeline.tfvars"
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*' # zip back everything up