version: 0.2  # version
phases:
  pre_build:
    commands:
      - echo WE ARE ENTERING THE PREBUILD PHASE...
      - terraform init
      - terraform validate
      
  build:
    commands:
      - terraform plan
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo Build completed on `date`
# artifacts:
#   files:
#     - '**/*' # zip back everything up